// ============================================
// Interview.model.js - Interview Database Schema
// ============================================
// Stores interview sessions with conversation
// history, questions, answers, and feedback.
// Reference: mongoose.Schema, Arrays - reference-mongodb.md
// ============================================

import mongoose from 'mongoose';

const interviewSchema = new mongoose.Schema(
  {
    // The user who took this interview
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },

    // The role being interviewed for (e.g., "Frontend Developer")
    role: {
      type: String,
      required: true,
    },

    // Resume text used to generate questions
    resumeText: {
      type: String,
      default: '',
    },

    // Current status of the interview
    status: {
      type: String,
      enum: ['in_progress', 'completed'],
      default: 'in_progress',
    },

    // Total number of questions planned for this interview
    totalQuestions: {
      type: Number,
      default: 5,
    },

    // Current question number (1-based)
    currentQuestion: {
      type: Number,
      default: 0,
    },

    // Array of questions generated by AI
    // Each question: { text, type, isCodeQuestion }
    questions: {
      type: Array,
      default: [],
    },

    // Conversation history (questions + answers)
    // Each message: { role: 'interviewer'|'candidate', content, timestamp }
    messages: {
      type: Array,
      default: [],
    },

    // Code submissions for coding questions
    // Each entry: { questionIndex, code, language, evaluation }
    codeSubmissions: {
      type: Array,
      default: [],
    },

    // Last audio (base64) for replay on page reload
    lastAudio: {
      type: String,
      default: '',
    },

    // AI-generated feedback after interview completion
    feedback: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    // Overall score (0-100)
    overallScore: {
      type: Number,
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

const Interview = mongoose.model('Interview', interviewSchema);

export default Interview;
